### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by zeke** [release-notifier/release-notifier#7]
When things don't work, the application logs are a good place to look to help diagnose the problem. Unfortunately I think @yoshuawuyts' [nanostate publish event](https://twitter.com/yoshuawuyts/status/958302255635189760) is lost in the ether.

By default, Heroku only retains the last [1500 log lines for an app](https://devcenter.heroku.com/articles/logging#log-history-limits), so I just set up a Papertrail log drain on the Heroku app that gives us the following:

Log volume per day: 100 MB
Search duration: 7 Days
Archive duration: 365 Days

So.. what kind of logging statements should we add to the app to make for useful debugging sessions? And what `LOG_LEVEL` should be used? I get that feeling that we'll burn up our allotment too quickly if its set to `trace`.

cc @gr2m @bkeepers

**Comment by gr2m** [comment]
I’d set it to debug and see how it goes?

**Comment by bkeepers** [comment]
I do `debug` on the apps I have running, and add debug statements whenever there's any significant logic.

**Comment by yoshuawuyts** [comment]
@zeke got [another issue with no output](https://github.com/choojs/nanoanimation/pull/5) - any idea what might be up?

**Comment by zeke** [comment]
Sorry @yoshuawuyts hadn't shipped https://github.com/release-notifier/release-notifier/pull/11 until just now so we were flying blind. Thanks for hanging in there! 🐈
